In [1]:
import cv2
import tensorflow as tf
from tensorflow.keras.models import load_model
import numpy as np
from pygame import mixer

pygame 2.1.0 (SDL 2.0.16, Python 3.8.8)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [2]:
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_eye.xml')
model = load_model(r'/Users/dosven/jupyter_note/Personal_Proj/ngugatlaixe/models/model.h5')

In [ ]:
mixer.init()
sound= mixer.Sound(r'/Users/dosven/jupyter_note/Personal_Proj/ngugatlaixe/alarm.wav')
cap = cv2.VideoCapture(0)
Score = 0
while True:
    ret, frame = cap.read()
    height,width = frame.shape[0:2]
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces= face_cascade.detectMultiScale(gray, scaleFactor= 1.2, minNeighbors=3)
    eyes= eye_cascade.detectMultiScale(gray, scaleFactor= 1.1, minNeighbors=1)
    
    cv2.rectangle(frame, (0,height-50),(200,height),(0,0,0),thickness=cv2.FILLED)
    
    for (x,y,w,h) in faces:
        cv2.rectangle(frame,pt1=(x,y),pt2=(x+w,y+h), color= (255,0,0), thickness=3 )
        
    for (ex,ey,ew,eh) in eyes:
        #cv2.rectangle(frame,pt1=(ex,ey),pt2=(ex+ew,ey+eh), color= (255,0,0), thickness=3 )
        
        # preprocessing steps
        eye= frame[ey:ey+eh,ex:ex+ew]
        eye= cv2.resize(eye,(80,80))
        eye= eye/255
        eye= eye.reshape(80,80,3)
        eye= np.expand_dims(eye,axis=0)
        # preprocessing is done now model prediction
        prediction = model.predict(eye)
        print(prediction)
        
        # if eyes are closed
        # if prediction[0][0]>0.30:
        if prediction[0][0]>0.10:
            cv2.putText(frame,'closed',(10,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(255,255,255),
                       thickness=1,lineType=cv2.LINE_AA)
            cv2.putText(frame,'Score'+str(Score),(100,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(255,255,255),
                       thickness=1,lineType=cv2.LINE_AA)
            Score=Score+1
            if(Score>15):
                try:
                    sound.play()
                except:
                    pass
            
        # if eyes are open
        # elif prediction[0][1]>0.90:
        elif prediction[0][1]>0.70:
            cv2.putText(frame,'open',(10,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(255,255,255),
                       thickness=1,lineType=cv2.LINE_AA)      
            cv2.putText(frame,'Score'+str(Score),(100,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(255,255,255),
                       thickness=1,lineType=cv2.LINE_AA)
            Score = Score-1
            if (Score<0):
                Score=0
            
        
    cv2.imshow('frame',frame)
    if cv2.waitKey(33) & 0xFF==ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows()

2021-12-06 15:15:38.928707: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)


[[0.55436367 0.4456363 ]]
[[0.32918936 0.67081064]]
[[0.18463133 0.81536865]]
[[0.6693601  0.33063993]]
[[0.55651075 0.44348928]]
[[0.5369919  0.46300814]]
[[0.63702875 0.36297125]]
[[0.5498404  0.45015964]]
[[0.9825598  0.01744025]]
[[0.9425454  0.05745464]]
[[0.36278155 0.6372185 ]]
[[0.37168145 0.62831855]]
[[0.12180338 0.87819666]]
[[0.7065284  0.29347157]]
[[0.9988211  0.00117894]]
[[0.68626904 0.31373098]]
[[0.14024457 0.85975546]]
[[0.66651547 0.33348453]]
[[0.38316053 0.6168394 ]]
[[0.74929625 0.25070375]]
[[0.52264255 0.47735748]]
[[0.3121077  0.68789226]]
[[0.9686393  0.03136073]]
[[0.9988527  0.00114731]]
[[0.7594693 0.2405307]]
[[0.89470804 0.10529193]]
[[0.8021557 0.1978443]]
[[0.9288744  0.07112562]]
[[0.98479766 0.01520233]]
[[0.35355833 0.6464417 ]]
[[0.10977472 0.8902253 ]]
[[0.7849557  0.21504435]]
[[0.70607287 0.29392716]]
[[0.6600454 0.3399546]]
[[0.71188045 0.28811952]]
[[0.9907357 0.0092643]]
[[0.9870077  0.01299236]]
[[0.9348982  0.06510182]]
[[0.9593108  0.04068

In [11]:
print(prediction[0][0])

0.673527
